SWerbeck/job-search-app

package.json, server/db/company.sql, server/db/seed.sql
got the many to many association working between users and companies
=> set up many to many association in seed file

server/api/routes/company.js, server/api/routes/routes.js
company routes tested and working
=> company express route working

.eslintrc.cjs, index.html, package-lock.json, package.json, server/api/index.js, server/api/routes/application.js, server/api/routes/company.js, server/api/routes/routes.js, server/api/routes/user.js, server/db/db.js
Switched all files to use import instead of const var = require('var'). All the red in vscode was driving me nuts so I made the switch. Everything should be working as intended. I also had to comment out the entire application.js file as I hadn't gotten to it yet, and still want to refactor that file. You'll also see in the routes.js file i commented out the import for the application.js
I also refactored all of the company.js route so it now uses async/await like the user.js file. Tested in postman and seems to be working.
=> switched to import over require and refactored company routes

package-lock.json, package.json, server/api/index.js, src/App.tsx
Had to npm install cors and axios to fetch data. Modified the index.js in the server file app.use(cors());
Modified the app.tsx on the front end and can console.log our user data. Also when we are retrieving data on the front end we have to specific localhost like http://localhost:3000/api/users
=> added cors and axios to package.json and can fetch data on front end

server/api/routes/application.js, server/api/routes/company.js, server/api/routes/contact.js, server/api/routes/queries/applicationqueries.js, server/api/routes/queries/companyqueries.js, server/api/routes/queries/contactqueries.js, server/api/routes/queries/userqueries.js, server/api/routes/user.js, server/db/application.sql
Refactored api routes to have sql queries in seperate .sql files
=> broke queries into seperate files

server/api/auth-middleware/authorization.js, server/api/routes/auth-routes.js, src/App.tsx, src/components/Login.tsx
=> madelogin form

server/api/index.js, src/components/Applicationscomponent.tsx, src/components/Login.tsx, src/custom-hooks/useRefreshToken.tsx, vite.config.ts
this is a good point to commit as the refresh token button is working. I plan on adding an instance of axios, rather than calling it directly and wanted a good starting point.
=> resfresh token button working

server/api/axios.js, server/api/index.js, server/api/routes/auth-routes.js, src/components/Applicationscomponent.tsx, src/components/Login.tsx, src/custom-hooks/useAxiosPrivate.tsx, src/custom-hooks/useRefreshToken.tsx
auth refactor from steven and louis code working
=> refactor-auth-working

server/api/auth-middleware/authorization.js, server/api/index.js, server/api/routes/application.js, server/api/routes/auth-routes.js, server/api/routes/routes.js, server/db/user.sql, src/components/Admin.tsx, src/components/Applicationscomponent.tsx, src/components/Login.tsx, src/custom-hooks/useRefreshToken.tsx
verifyJWT works when using as a middlewear for /applications/user/:id
=> new backend with login, refresh, logout, and verifyJWT working

server/api/auth-middleware/authorization.js, server/api/routes/auth-routes.js, src/App.tsx, src/components/Applicationscomponent.tsx, src/components/Login.tsx, src/components/Navbar.tsx, src/components/PersistantLogin.tsx, src/custom-hooks/useRefreshToken.tsx
persistant login working but navigating to / on refresh. need to figure out the navigate
=> persistant login working but navigating to / on refresh

server/api/routes/queries/applicationqueries.js, server/db/application.sql, server/db/contact.sql, server/db/user.sql, src/App.tsx, src/components/Companiescomponent.tsx, src/components/Contactscomponent.tsx, src/components/Navbar.tsx, src/components/SingleCompany.tsx, src/components/cards/Companiescard.tsx
edited enums on backend and started singleCompany component
=> edited enums on backend and started singleCompany component

NOTES.md, src/App.tsx, src/components/Applicationscomponent.tsx, src/components/GuestHome.tsx, src/components/Navbar.tsx, src/components/RequireAuth.tsx
guest front end routes displaying before login
=> guest front end routes displaying before login

src/components/Applicationscomponent.tsx, src/components/Companiescomponent.tsx, src/components/Contactscomponent.tsx, src/store/userAppsSlice.ts
delete application working on front end through redux state. Also companies are now displayed through fetching the users applications.
=> delete application working through redux reducer

src/components/Colortestcomponent.tsx, src/components/SingleCompany.tsx, src/components/cards/Companiescard.tsx, src/components/cards/SingleCompanyCard.tsx
display single company page and created card
=> display single company page and created card

src/components/Applicationscomponent.tsx, src/components/SingleCompany.tsx, src/store/userAppsSlice.ts
got the edit job-position working on front and back end through redux. next steps need to be able to edit everything else on the front and back end
=> edit job-position working on front and back end

src/components/cards/EditCompanyCard.tsx, src/components/cards/SingleCompanyCard.tsx
we needed to use map instead of foreach lol
=> got contact info saved to local hook

server/api/routes/application.js, src/App.tsx, src/components/ApplicationForm.tsx, src/components/Applicationscomponent.tsx, src/store/userAppsSlice.ts
add application form working on backend with ui bug
need to fix reduxx
=> add application form working on backend with ui bug

src/components/ApplicationForm.tsx, src/components/Applicationscomponent.tsx, src/components/cards/SingleCompanyCard.tsx, src/store/userAppsSlice.ts
fixed add application bug on front end. also company displays all jobs correctly now.
=> fixed add application bug on front end

server/api/routes/queries/applicationqueries.js, src/components/Applicationscomponent.tsx, src/components/Singleapplicationcomponent.tsx, src/components/cards/SingleApplicationCard.tsx
moved delete button to single application and also edit api for applications to include more data
=> moved delete button to single application

server/api/routes/auth-routes.js, src/components/Login.tsx, src/components/Navbar.tsx
fixed login bug so error message populates from backend. didn't actually get to any css on this commit.
=> fixed login bug so error message populates from backend

src/App.tsx, src/components/Applicationscomponent.tsx, src/components/cards/EditApplicationCard.tsx, src/components/cards/SingleApplicationCard.tsx, src/store/userAppsSlice.ts
added css and need to fix single company bug
=> added application css and found single company bug

src/components/ApplicationForm.tsx, src/components/cards/SingleApplicationCard.tsx, src/store/userAppsSlice.ts
solved single app comanyName display bug
also found a bug where the contacts do not get displayed on the single app page but appear after a hard reload. Will need to troubleshoot more and try and solve the same way with the companyName display bug. There is commented out code in the addUserApp reducer that might be useful.
=> solved single app comanyName display bug

src/store/userAppsSlice.ts
fixed minor company display bug
=> fixed minor company display bug

NOTES.md, src/components/Applicationscomponent.tsx, src/components/Singleapplicationcomponent.tsx, src/components/cards/SingleApplicationCard.tsx, src/store/userAppsSlice.ts
delete button working and single app displays all of the data needed.
=> delete button working and single app displays

server/api/routes/application.js, server/api/routes/queries/applicationqueries.js, src/components/cards/EditApplicationCard.tsx, src/components/cards/SingleApplicationCard.tsx, src/store/userAppsSlice.ts
Now able to edit job title, application info (like a description), company website, and the status of your application. 
status is an enum dropdown with the only options as active, interviewing, and closed.
Also defaultValues are in the form so if a user submits without a value it should still make the request to the backend.
=> added more app form fields

server/db/application.sql, src/components/Colortestcomponent.tsx, src/components/HomePage.tsx, src/components/Login.tsx, src/components/Navbar.tsx, tailwind.config.js
more data for the guest and fixed some navbar css. Will need to do lots of css for different screen sizes.
=> navbar css and seeded more guest data

src/App.tsx, src/components/Applicationscomponent.tsx, src/components/HomePage.tsx, src/components/Login.tsx, src/components/Navbar.tsx, tailwind.config.js
application page and nav bar mostly responsive. Need to handle error messages on the navbar when login(css) and main application dates responsiveness(css).
=> application page responsive

src/components/Admin.tsx
test to make sure my git is working
=> test-push-from-branch

server/api/routes/user.js, src/components/Applicationscomponent.tsx, src/components/Signup.tsx
finished styling sign up form. some minor changes might need to be changed depending on preference.
=> finished styking sign up form

server/api/routes/guest-routes.js, server/api/routes/queries/guestqueries.js, src/components/Navbar.tsx, src/components/SingleContact.tsx
edited single contact and its api call. Found we were using a not so great api end point. Hard coded the guest contact api call so it works for guest and then did one for the logged in user.
=> edited single contact and its api call

src/components/SingleCompany.tsx, src/components/SingleContact.tsx, src/components/cards/EditContactCard.tsx, src/components/cards/SingleContactCard.tsx
moved single contact logic into a card and also built an edit card component. Currently the edit component will just toggle back and forth between the card and an "edit mode" but no changes can be made. Next step is going to be getting the edit form working and able to make api calls.
=> moved single contact logic into a card

src/components/cards/EditApplicationCard.tsx, src/components/cards/EditContactCard.tsx
Styled the edit contacts page so it looks similar or exactly the same as the edit application page. 
Also found and error with the toast notification when you delete an application. There is an x in the toast notification and if you click x instead of yes or no to delete the app would be frozen. This was because we were not setting the ToastId to null in the onClose function. I added that line and the bug is fixed. 
I also changed the toast notification so the message appears in the center of the screen and not in the top right like before.
=> styled edit contact page and fixed toast error

NOTES.md, server/api/routes/contact.js, src/App.tsx, src/components/ContactForm.tsx, src/components/Contactscomponent.tsx, src/components/SingleContact.tsx
post contact working on frontend. Also added to notes for todos for next week.
=> post contact working on frontend
